import { ChecklistItem } from "@/lib/inspection-data"
import { forwardRef } from "react"

interface PdfReportProps {
  items: ChecklistItem[]
  photoMap: Record<number, string[]>
  vesselName: string
  captainName: string
  inspectionDate: string
  inspectorName: string
}

export const PdfReport = forwardRef<HTMLDivElement, PdfReportProps>(
  ({ items, photoMap, vesselName, captainName, inspectionDate, inspectorName }, ref) => {
    // Only include items that are not 'select' (i.e. have a determined status)
    const checkedItems = items.filter(item => item.status !== 'select')

    return (
      <div ref={ref} className="bg-[#ffffff] text-[#000000] p-8" style={{ width: '800px', minHeight: '1122px' }}>
        {/* Header */}
        <div className="flex justify-between items-center border-b-2 border-[#1e293b] pb-4 mb-6">
          <div>
            <h1 className="text-3xl font-bold uppercase tracking-wider text-[#1e293b]">Inspection Report</h1>
            <p className="text-sm text-[#64748b] mt-1">Generated by SPARK Inspection System</p>
          </div>
          <div className="bg-[#000000] p-3 px-4 rounded-xl flex items-center justify-center">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/spark_logo3.png" alt="SPARK Logo" className="h-13 object-contain" />
          </div>
        </div>

        {/* Vessel Details */}
        <div className="grid grid-cols-2 gap-4 mb-8 bg-[#f8fafc] p-5 rounded-xl border border-[#e2e8f0] shadow-sm">
          <div>
            <span className="block text-xs font-semibold text-[#64748b] uppercase tracking-wider">Vessel Name</span>
            <span className="block text-lg font-medium text-[#0f172a]">{vesselName || "N/A"}</span>
          </div>
          <div>
            <span className="block text-xs font-semibold text-[#64748b] uppercase tracking-wider">Captain</span>
            <span className="block text-lg font-medium text-[#0f172a]">{captainName || "N/A"}</span>
          </div>
          <div>
            <span className="block text-xs font-semibold text-[#64748b] uppercase tracking-wider">Inspection Date</span>
            <span className="block text-lg font-medium text-[#0f172a]">{inspectionDate || "N/A"}</span>
          </div>
          <div>
            <span className="block text-xs font-semibold text-[#64748b] uppercase tracking-wider">Inspector</span>
            <span className="block text-lg font-medium text-[#0f172a]">{inspectorName || "N/A"}</span>
          </div>
        </div>

        {/* Summary */}
        <div className="mb-8">
          <h2 className="text-lg font-semibold text-[#1e293b] mb-3 border-b border-[#e2e8f0] pb-2">Inspection Summary</h2>
          <div className="flex gap-4">
            <div className="bg-[#ecfdf5] border border-[#a7f3d0] rounded-lg p-3 flex-1 text-center">
              <span className="block text-2xl font-bold text-[#047857]">{checkedItems.filter(i => i.status === 'ok').length}</span>
              <span className="text-xs font-semibold text-[#059669] uppercase">OK</span>
            </div>
            <div className="bg-[#fffbeb] border border-[#fde68a] rounded-lg p-3 flex-1 text-center">
              <span className="block text-2xl font-bold text-[#b45309]">{checkedItems.filter(i => i.status === 'observation').length}</span>
              <span className="text-xs font-semibold text-[#d97706] uppercase">Observations</span>
            </div>
            <div className="bg-[#fff1f2] border border-[#fecdd3] rounded-lg p-3 flex-1 text-center">
              <span className="block text-2xl font-bold text-[#be123c]">{checkedItems.filter(i => i.status === 'deficiency').length}</span>
              <span className="text-xs font-semibold text-[#e11d48] uppercase">Deficiencies</span>
            </div>
          </div>
        </div>

        {/* Items List */}
        <div className="flex flex-col gap-6">
          <h2 className="text-lg font-semibold text-[#1e293b] border-b border-[#e2e8f0] pb-2">Detailed Findings</h2>
          {checkedItems.length === 0 ? (
            <p className="text-[#64748b] italic text-sm">No items have been checked yet.</p>
          ) : (
            checkedItems.map((item) => {
              const photos = photoMap[item.id] || []
              return (
                <div key={item.id} className="border border-[#cbd5e1] rounded-lg overflow-hidden shadow-sm" style={{ pageBreakInside: 'avoid' }}>
                  <div className="bg-[#f1f5f9] p-3 border-b border-[#cbd5e1] flex justify-between items-start">
                    <span className="font-semibold text-sm text-[#1e293b] pr-4">
                      {item.section} - {item.id}
                    </span>
                    <span className={`px-2.5 py-1 text-[11px] font-bold rounded-full uppercase tracking-wider shrink-0 ${item.status === 'ok' ? 'bg-[#d1fae5] text-[#065f46] border border-[#a7f3d0]' :
                      item.status === 'deficiency' ? 'bg-[#ffe4e6] text-[#9f1239] border border-[#fecdd3]' :
                        item.status === 'observation' ? 'bg-[#fef3c7] text-[#92400e] border border-[#fde68a]' :
                          'bg-[#f1f5f9] text-[#1e293b] border border-[#e2e8f0]'
                      }`}>
                      {item.status}
                    </span>
                  </div>
                  <div className="p-4 bg-[#ffffff]">
                    <p className="text-sm font-medium text-[#1e293b] mb-3 leading-relaxed">{item.question}</p>
                    {item.remarks && (
                      <div className="mt-3 text-sm text-[#334155] bg-[#fffbeb] border border-[#fef3c7] p-3 rounded-md">
                        <span className="font-semibold text-[#78350f] block mb-1">Inspector Remarks: </span>
                        {item.remarks}
                      </div>
                    )}
                    {photos.length > 0 && (
                      <div className="mt-4 border-t border-[#f1f5f9] pt-4">
                        <span className="text-xs font-semibold text-[#64748b] uppercase tracking-wider block mb-2">Attached Evidence</span>
                        <div className="grid grid-cols-2 gap-3">
                          {photos.map((photo, i) => (
                            <div key={i} className="border border-[#e2e8f0] rounded p-1 bg-[#f8fafc]">
                              <img
                                src={photo}
                                alt={`Evidence ${i + 1}`}
                                className="w-full h-auto object-contain rounded"
                                style={{ maxHeight: '200px' }}
                              />
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )
            })
          )}
        </div>
      </div>
    )
  }
)
PdfReport.displayName = 'PdfReport'
